---
kind: Deployment

apiVersion: apps/v1
metadata:
  name: {{ .Chart.Name }}-deployment
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Values.container.name }}
        image: {{ .Values.container.image }}
        command: 
          - "/bin/bash"
          - "-c"
          - "{{ .Values.container.command }}"
        envFrom:
        - configMapRef:
            name: {{ .Values.container.envConfigMap }}
        volumeMounts:
        - name: {{ .Values.container.volumeMounts.name }}
          mountPath: {{ .Values.container.volumeMounts.mountPath }}
      volumes:
      - name: {{ .Values.volumes.name }}
        configMap:
          name: {{ .Values.volumes.configMap }}
